#!/bin/bash
if [[ $# -eq 1 ]]; then
    sudo python3.8 ~/.bin/Directory-Compress-py/dir_comp_script.py $1
elif [[ $# -ne 3 ]]; then
    sudo python3.8 ~/.bin/Directory-Compress-py/dir_comp_script.py $1 $2 $3
fi

