#!/bin/bash
if [[ $# -eq 1 ]]; then
    sudo python3 /home/.bin/dir_comp_script.py $1
elif [[ $# -ne 3 ]]; then
    sudo python3 /home/.bin/dir_comp_script.py $1 $2
elif [[ $# -ne 2 ]]; then
    sudo python3 /home/.bin/dir_comp_script.py $1 $2 $3
fi

